### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by josephpaturi** [razinc/fplysis#24]
`❯ poetry run python analysis_team.py
Traceback (most recent call last):
  File "/Users/Documents/FPL/fplysis/analysis_team.py", line 5, in <module>
    from custom.players import Players
  File "/Users/Documents/FPL/fplysis/custom/players.py", line 12, in <module>
    from custom.teams import teams
  File "/Users/Documents/FPL/fplysis/custom/teams.py", line 41, in <module>
    teams = builder()
            ^^^^^^^^^
  File "/Users/Documents/FPL/fplysis/custom/teams.py", line 16, in builder
    fdr_h = round(fdr[team["name"]]["all"]["H"], 2)
                  ~~~^^^^^^^^^^^^^^
KeyError: 'Ipswich'`

**Comment by josephpaturi** [comment]
What do i fill in here ? 

`COOKIE = """datadome=;pl_profile="""`

**Comment by razinc** [comment]
> `❯ poetry run python analysis_team.py Traceback (most recent call last): File "/Users/Documents/FPL/fplysis/analysis_team.py", line 5, in <module> from custom.players import Players File "/Users/Documents/FPL/fplysis/custom/players.py", line 12, in <module> from custom.teams import teams File "/Users/Documents/FPL/fplysis/custom/teams.py", line 41, in <module> teams = builder() ^^^^^^^^^ File "/Users/Documents/FPL/fplysis/custom/teams.py", line 16, in builder fdr_h = round(fdr[team["name"]]["all"]["H"], 2) ~~~^^^^^^^^^^^^^^ KeyError: 'Ipswich'`

Let's focus on this error first. May I know what is your full command?

**Comment by razinc** [comment]
The `KeyError` error is caused by outdated `fpl` package. I attached the latest `utils.py` which has
[utils.zip](https://github.com/user-attachments/files/16734936/utils.zip)
 the updated information for 24/25 season. Can you please try to:

1. Download it.
2. Unzip it.
3. Replace your `utils.py` with the unzipped files. The original files should be somewhere here: `/home/$USER/.cache/pypoetry/virtualenvs/fplysis-*/lib/python3.12/site-packages/fpl/utils.py`
4. Rerun with the command in my previous comment.

**Comment by josephpaturi** [comment]
Thanks for the response. It worked after updating the `utils`

**Comment by razinc** [comment]
Great. If you want to use the username & password instead of your user ID, the value for `COOKIE` can be obtained from the developer tool.

**Comment by josephpaturi** [comment]
thanks .. figured out that one.
I think the XP needs a bit tuning

**Comment by razinc** [comment]
Yeah. The expected points are from the official API. I haven't checked if there are any better alternatives.
